SITE_NAME: "studio.local.openedx.io"
BOOK_URL: ""
LOG_DIR: "/openedx/data/logs"
LOGGING_ENV: "sandbox"
OAUTH_OIDC_ISSUER: "http://local.openedx.io/oauth2"
PLATFORM_NAME: "Hutech"
FEATURES:
  
  
  CERTIFICATES_HTML_VIEW: true
  PREVIEW_LMS_BASE: "preview.local.openedx.io"
  ENABLE_CSMH_EXTENDED: false
  ENABLE_LEARNER_RECORDS: false
  ENABLE_LIBRARY_INDEX: true
  MILESTONES_APP: true
  ENABLE_PREREQUISITE_COURSES: true
LMS_ROOT_URL: "http://local.openedx.io"
CMS_ROOT_URL: "http://studio.local.openedx.io"
CMS_BASE: "studio.local.openedx.io"
LMS_BASE: "local.openedx.io"
CONTACT_EMAIL: "contact@local.openedx.io"
CELERY_BROKER_TRANSPORT: "redis"
CELERY_BROKER_HOSTNAME: "redis:6379"
CELERY_BROKER_VHOST: "0"
CELERY_BROKER_USER: ""
CELERY_BROKER_PASSWORD: ""
ALTERNATE_WORKER_QUEUES: "lms"
ENABLE_COMPREHENSIVE_THEMING: true
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: "smtp"
EMAIL_PORT: 8025
EMAIL_USE_TLS: false
HTTPS: "off"
LANGUAGE_CODE: "vi"
SESSION_COOKIE_DOMAIN: "studio.local.openedx.io"

SECRET_KEY: "l2gFzmQ4r8qEJka7rNC4gQBa"
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
DOC_STORE_CONFIG: null
XQUEUE_INTERFACE:
  django_auth: null
  url: null
DATABASES:
  default:
    ENGINE: "django.db.backends.mysql"
    HOST: "mysql"
    PORT: 3306
    NAME: "openedx"
    USER: "openedx"
    PASSWORD: "lx9i116C"
    ATOMIC_REQUESTS: true
    OPTIONS:
      init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
      charset: "utf8mb4"
EMAIL_HOST_USER: ""
EMAIL_HOST_PASSWORD: ""
