CMS_HOST: studio.local.openedx.io
CMS_OAUTH2_SECRET: 95Rv6FW0j5l5FLtXpqOVvS8p
CONTACT_EMAIL: contact@local.openedx.io
ENABLE_HTTPS: false
ID: t3qQsIk5xhTf5w3dERgMXnL7
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAwGVqOZVjkyA5IBLi60oYEkiWaXvt945NmOaq7Od88/lfkIEt

  ShL9ZnIbS5aHZTHibdKrUjJvHJcaHCwdM6H0GdLoLJ2KI2mZF2xuguhGT0f/HbhU

  YQ5SSqjyaRQH69H5GeI+gq0PyhINAP0EC0iZEiGH07DbmFOwLMBAdUZ9Xyxk4ZIF

  PFFjMgfbmrzxUp0ba79b12IHMf5EDcyOUDUDZYcjaKC3zsmuoIHK4MvLDfjg2FeH

  pvYhmguTwfsR/Q5ZSYXNlRHarHTp5CPrd6yfH0pFwQzqqKO9TTAPEhTPL4q24jO9

  ux4sh9wEAh2vChcGtjk6pWxCBRifNnZxYHdRsQIDAQABAoIBAE3w57MTO2cPX0UI

  kaf6+LxzboemHnWyzum5zJWzg7G8nQPH6QaAoeo+IKOjBA+xQUb3WNMwPkYJSpkO

  H/haTC6n+8mTOrJ05YGROkXK/izBAG9UTM6SxDCdt7Js3HaitfTP7D35CRP18xGq

  7lf53ZT0Q3e1RoizooPGkHZSC5khiYgH0GGvVNU5v7psNslDtG90QnYRNMfqoZYa

  4dv1NSH8dBthU+nj1gBIzl2oNQ7G9k78CtfK1MrBjVUqRzRKu7G6YM5UZIVp54Bp

  7kI1rRlYsUl1hjrplHqD+CRd9xRnmqUPQdjD411qXrNQSHcrJRHLVZs7PEeufNF8

  yLiwb/8CgYEA1ySMzqs/HRHINEg0U7qKJxALjWgbPiCBJjzrb5L0IXf5nVe9LGyJ

  ZVef2nQ+9LsDiOh0hdQdEJJVR/8P3BuoWWsb8xBTKMv5azE1mSbrfnzV4RJ+iwTA

  DFGZkqf9INF7hR9fQt59Y7y7+QFa22OZnjjEgDRedQtO5/3ATV0OxQsCgYEA5O8C

  BH5vehQX+chCAx5kbP9EzeV4lH84Pu9oS/fkkgoAdbWUwjj/qMvGVOScgkCeT4jE

  lRGoF5YKLI1CCVKJqXMQd/FPq1Omy3atK9YTQNvxyAVYFdLb9Y7wKwoMdnZVDYc9

  ui2fJhIeoRbmazqThoRYq4KA1/lBSmrU3m8rgbMCgYAVVoawqMNlurHEnbSy6Tly

  jmDW8ZBiJQ8qH7iqJEUaXK/hLyaQFWO7LWmpXQYxd6ruFUAZVeRcFGdo8J8+EXAt

  DjaDcQcOcMyYGRVbz0RkEzWTUSZD24DAuAcnSIoOizhZB7eHBlIhZkKue7frMoG1

  86Npo8gKi8iTsdM02Rnx6QKBgENhWU2rTPI4Ycoht9QlKNev1jdnl7LVMt/LJP5f

  CsY07We3tv3nOtAakdhApRPtIuszzPA3DytJ/NqaBNqrkVrvQ+SZgKJjb48o8dUa

  H/aSBbqiYAekVRsUI/n27i4bq/LcYD2g2duhr6QoEk9zISKRZ2urcHKgqSfXA6oo

  PDzjAoGAQ8pbyrwlgjo/Ol9PZS5N9lLi4F3ch5M3idUjisd7Wyd7JO+MX0SSF1BS

  IznRHSLUiNJ7Q7ch5Uy9zomcbAqQzVmB/7IiETyCSsa9AjcLE67raeNLC3cqnKUO

  QJLoEzPQmGc5k94W4oo+CvXGL38Yi6Fgc0RDrIK1jn4h9gVdky0=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: vi
LMS_HOST: local.openedx.io
MEILISEARCH_API_KEY: e90bc3188493cb03815bf040a02ed71b33622aa7dba324cadc1789b9bc74621a
MEILISEARCH_API_KEY_UID: 52c40358-0643-471f-af31-9dfaf452192f
MEILISEARCH_MASTER_KEY: AwrIf1W4tAOky8C1qDkYg4fc
MOUNT_EDX_PLATFORM: /home/hoangsonsdk/edx-platform
MYSQL_ROOT_PASSWORD: Deadthemonkiller123
OPENEDX_MYSQL_PASSWORD: lx9i116C
OPENEDX_SECRET_KEY: l2gFzmQ4r8qEJka7rNC4gQBa
PLATFORM_NAME: Hutech
PLUGINS:
- mfe
- indigo
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
